apiVersion: v1
kind: Service
metadata:
  name: {{ include "cowrie.fullname" . }}
  labels:
    {{- include "cowrie.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: ssh-honeypot
  selector:
    {{- include "cowrie.selectorLabels" . | nindent 4 }}
